from . import base
from . import ir_actions
from . import ir_http
from . import ir_model_access
from . import ir_ui_menu
from . import ir_ui_view
from . import model_method_execution_right
from . import res_groups
from . import res_role
from . import res_role_acl
from . import res_users
from . import security_policy_tag
from . import view_model_operation
from . import view_modifier_rule
from . import view_type_attribute
