from . import base
from . import ir_actions
from . import ir_model_access
from . import ir_ui_menu
from . import ir_ui_view
from . import res_groups
from . import res_role
from . import res_role_acl
from . import res_users
from . import security_policy_tag
from . import web_modifier_rule
